using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;


namespace Redbox.HAL.MSHALTester
{
    public class GearAndMotorProperties : Form
    {
        private IContainer components;
        private Button button1;
        private Button button2;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private GroupBox groupBox5;
        private Label label3;
        private Label label2;
        private Label label1;
        private Label label4;
        private Label label8;
        private Label label7;
        private Label label6;
        private Label label5;
        private TextBox textBox4;
        private TextBox textBox3;
        private TextBox textBox2;
        private TextBox textBox1;
        private TextBox textBox8;
        private TextBox textBox7;
        private TextBox textBox6;
        private TextBox textBox5;
        private Label label11;
        private Label label10;
        private Label label9;
        private Label label14;
        private Label label13;
        private Label label12;
        private TextBox textBox11;
        private TextBox textBox10;
        private TextBox textBox9;
        private TextBox textBox14;
        private TextBox textBox13;
        private TextBox textBox12;

        public GearAndMotorProperties() => this.InitializeComponent();

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.button1 = new Button();
            this.button2 = new Button();
            this.groupBox1 = new GroupBox();
            this.groupBox2 = new GroupBox();
            this.groupBox3 = new GroupBox();
            this.groupBox4 = new GroupBox();
            this.groupBox5 = new GroupBox();
            this.label1 = new Label();
            this.label2 = new Label();
            this.label3 = new Label();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label6 = new Label();
            this.label7 = new Label();
            this.label8 = new Label();
            this.textBox1 = new TextBox();
            this.textBox2 = new TextBox();
            this.textBox3 = new TextBox();
            this.textBox4 = new TextBox();
            this.textBox5 = new TextBox();
            this.textBox6 = new TextBox();
            this.textBox7 = new TextBox();
            this.textBox8 = new TextBox();
            this.label9 = new Label();
            this.label10 = new Label();
            this.label11 = new Label();
            this.label12 = new Label();
            this.label13 = new Label();
            this.label14 = new Label();
            this.textBox9 = new TextBox();
            this.textBox10 = new TextBox();
            this.textBox11 = new TextBox();
            this.textBox12 = new TextBox();
            this.textBox13 = new TextBox();
            this.textBox14 = new TextBox();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.SuspendLayout();
            this.button1.Location = new Point(140, 530);
            this.button1.Name = "button1";
            this.button1.Size = new Size(75, 56);
            this.button1.TabIndex = 1;
            this.button1.Text = "Ok";
            this.button1.UseVisualStyleBackColor = true;
            this.button2.Location = new Point(303, 530);
            this.button2.Name = "button2";
            this.button2.Size = new Size(75, 56);
            this.button2.TabIndex = 2;
            this.button2.Text = "Cancel";
            this.button2.UseVisualStyleBackColor = true;
            this.groupBox1.Controls.Add((Control)this.textBox4);
            this.groupBox1.Controls.Add((Control)this.textBox3);
            this.groupBox1.Controls.Add((Control)this.textBox2);
            this.groupBox1.Controls.Add((Control)this.textBox1);
            this.groupBox1.Controls.Add((Control)this.label4);
            this.groupBox1.Controls.Add((Control)this.label3);
            this.groupBox1.Controls.Add((Control)this.label2);
            this.groupBox1.Controls.Add((Control)this.label1);
            this.groupBox1.Location = new Point(27, 24);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(200, 142);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Gear X Properties";
            this.groupBox2.Controls.Add((Control)this.textBox8);
            this.groupBox2.Controls.Add((Control)this.textBox7);
            this.groupBox2.Controls.Add((Control)this.textBox6);
            this.groupBox2.Controls.Add((Control)this.textBox5);
            this.groupBox2.Controls.Add((Control)this.label8);
            this.groupBox2.Controls.Add((Control)this.label7);
            this.groupBox2.Controls.Add((Control)this.label6);
            this.groupBox2.Controls.Add((Control)this.label5);
            this.groupBox2.Location = new Point(292, 24);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(214, 142);
            this.groupBox2.TabIndex = 4;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Gear Y Properties";
            this.groupBox3.Controls.Add((Control)this.textBox11);
            this.groupBox3.Controls.Add((Control)this.textBox10);
            this.groupBox3.Controls.Add((Control)this.textBox9);
            this.groupBox3.Controls.Add((Control)this.label11);
            this.groupBox3.Controls.Add((Control)this.label10);
            this.groupBox3.Controls.Add((Control)this.label9);
            this.groupBox3.Location = new Point(15, 32);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(200, 114);
            this.groupBox3.TabIndex = 5;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Init Speed";
            this.groupBox4.Controls.Add((Control)this.groupBox5);
            this.groupBox4.Controls.Add((Control)this.groupBox3);
            this.groupBox4.Location = new Point(27, 185);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(491, 163);
            this.groupBox4.TabIndex = 6;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Motor X ";
            this.groupBox5.Controls.Add((Control)this.textBox14);
            this.groupBox5.Controls.Add((Control)this.textBox13);
            this.groupBox5.Controls.Add((Control)this.textBox12);
            this.groupBox5.Controls.Add((Control)this.label14);
            this.groupBox5.Controls.Add((Control)this.label13);
            this.groupBox5.Controls.Add((Control)this.label12);
            this.groupBox5.Location = new Point(265, 32);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(200, 114);
            this.groupBox5.TabIndex = 6;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Move Speed";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(12, 26);
            this.label1.Name = "label1";
            this.label1.Size = new Size(57, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Step Ratio";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(12, 54);
            this.label2.Name = "label2";
            this.label2.Size = new Size(61, 13);
            this.label2.TabIndex = 1;
            this.label2.Text = "Pulse Ratio";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(12, 83);
            this.label3.Name = "label3";
            this.label3.Size = new Size(75, 13);
            this.label3.TabIndex = 2;
            this.label3.Text = "Encoder Ratio";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(12, 112);
            this.label4.Name = "label4";
            this.label4.Size = new Size(82, 13);
            this.label4.TabIndex = 3;
            this.label4.Text = "Step Resolution";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(17, 26);
            this.label5.Name = "label5";
            this.label5.Size = new Size(57, 13);
            this.label5.TabIndex = 0;
            this.label5.Text = "Step Ratio";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(17, 54);
            this.label6.Name = "label6";
            this.label6.Size = new Size(61, 13);
            this.label6.TabIndex = 1;
            this.label6.Text = "Pulse Ratio";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(17, 83);
            this.label7.Name = "label7";
            this.label7.Size = new Size(75, 13);
            this.label7.TabIndex = 2;
            this.label7.Text = "Encoder Ratio";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(17, 112);
            this.label8.Name = "label8";
            this.label8.Size = new Size(82, 13);
            this.label8.TabIndex = 3;
            this.label8.Text = "Step Resolution";
            this.textBox1.Location = new Point(113, 23);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(81, 20);
            this.textBox1.TabIndex = 4;
            this.textBox2.Location = new Point(113, 51);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(81, 20);
            this.textBox2.TabIndex = 5;
            this.textBox3.Location = new Point(113, 77);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new Size(81, 20);
            this.textBox3.TabIndex = 6;
            this.textBox4.Location = new Point(113, 105);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new Size(81, 20);
            this.textBox4.TabIndex = 7;
            this.textBox5.Location = new Point(119, 23);
            this.textBox5.Name = "textBox5";
            this.textBox5.Size = new Size(81, 20);
            this.textBox5.TabIndex = 4;
            this.textBox6.Location = new Point(119, 54);
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new Size(81, 20);
            this.textBox6.TabIndex = 5;
            this.textBox7.Location = new Point(119, 80);
            this.textBox7.Name = "textBox7";
            this.textBox7.Size = new Size(80, 20);
            this.textBox7.TabIndex = 6;
            this.textBox8.Location = new Point(119, 109);
            this.textBox8.Name = "textBox8";
            this.textBox8.Size = new Size(81, 20);
            this.textBox8.TabIndex = 7;
            this.label9.AutoSize = true;
            this.label9.Location = new Point(6, 26);
            this.label9.Name = "label9";
            this.label9.Size = new Size(27, 13);
            this.label9.TabIndex = 0;
            this.label9.Text = "Low";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(6, 53);
            this.label10.Name = "label10";
            this.label10.Size = new Size(29, 13);
            this.label10.TabIndex = 1;
            this.label10.Text = "High";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(6, 81);
            this.label11.Name = "label11";
            this.label11.Size = new Size(66, 13);
            this.label11.TabIndex = 2;
            this.label11.Text = "Acceleration";
            this.label12.AutoSize = true;
            this.label12.Location = new Point(17, 26);
            this.label12.Name = "label12";
            this.label12.Size = new Size(27, 13);
            this.label12.TabIndex = 0;
            this.label12.Text = "Low";
            this.label13.AutoSize = true;
            this.label13.Location = new Point(17, 53);
            this.label13.Name = "label13";
            this.label13.Size = new Size(32, 13);
            this.label13.TabIndex = 1;
            this.label13.Text = "High ";
            this.label14.AutoSize = true;
            this.label14.Location = new Point(17, 81);
            this.label14.Name = "label14";
            this.label14.Size = new Size(66, 13);
            this.label14.TabIndex = 2;
            this.label14.Text = "Acceleration";
            this.textBox9.Location = new Point(98, 23);
            this.textBox9.Name = "textBox9";
            this.textBox9.Size = new Size(81, 20);
            this.textBox9.TabIndex = 3;
            this.textBox10.Location = new Point(98, 53);
            this.textBox10.Name = "textBox10";
            this.textBox10.Size = new Size(81, 20);
            this.textBox10.TabIndex = 4;
            this.textBox11.Location = new Point(98, 81);
            this.textBox11.Name = "textBox11";
            this.textBox11.Size = new Size(81, 20);
            this.textBox11.TabIndex = 5;
            this.textBox12.Location = new Point(113, 23);
            this.textBox12.Name = "textBox12";
            this.textBox12.Size = new Size(81, 20);
            this.textBox12.TabIndex = 3;
            this.textBox13.Location = new Point(113, 50);
            this.textBox13.Name = "textBox13";
            this.textBox13.Size = new Size(81, 20);
            this.textBox13.TabIndex = 4;
            this.textBox14.Location = new Point(113, 78);
            this.textBox14.Name = "textBox14";
            this.textBox14.Size = new Size(81, 20);
            this.textBox14.TabIndex = 5;
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(819, 610);
            this.Controls.Add((Control)this.groupBox4);
            this.Controls.Add((Control)this.groupBox2);
            this.Controls.Add((Control)this.groupBox1);
            this.Controls.Add((Control)this.button2);
            this.Controls.Add((Control)this.button1);
            this.Name = nameof(GearAndMotorProperties);
            this.Text = nameof(GearAndMotorProperties);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
